### ISSUE TITLE
[opcEars] Comparator does not work

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#10]
Hi all,

somehow the != comparator does not work when looping over beliefs in wrdac/opcEars. I did a quick fix in https://github.com/robotology/wysiwyd/commit/0756ec38d164a6d1abc7aabd7b2bd69b4c6a1328 to check for 
```size > 0```
But it should be done properly, otherwise someone else might run into this issue sooner or later.

Would be great if someone from WP5 could have a look at it :).

Thanks,
Tobias

**Comment by pattacini** [comment]
Any update on this? Otherwise I think we can close it.

**Comment by Tobias-Fischer** [comment]
I don't think it should be closed yet. The comparator still doesn't work, and it is just a matter of time until someone else runs into issues related with this. And nobody likes SegFaults, right?!? :)

**Comment by pattacini** [comment]
Then we should assign to someone of **WP5**, otherwise it won't get solved ever :smirk:

**Comment by pattacini** [comment]
@jypuigbo @clement-moulin-frier would you be willing to solve this?

**Comment by gregoire-pointeau** [comment]
Hum, I can take a look at it this week if you want. Because I don't think
Jordi or Clement are used to OPCEARS.

2015-04-27 13:33 GMT+02:00 Ugo Pattacini <notifications@github.com>:

> @jypuigbo <https://github.com/jypuigbo> @clement-moulin-frier
> <https://github.com/clement-moulin-frier> would you be willing to solve
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/wysiwyd/issues/10#issuecomment-96615959>.
>



-- 
Grégoire Pointeau

Robot Cognition Laboratory
Stem Cell and Brain Research Institute
INSERM U846
Department of Integrative Neuroscience
18, avenue Doyen Lépine
69675 Bron Cedex

**Comment by pattacini** [comment]
Fine with me, thanks @gregoire-pointeau

**Comment by Tobias-Fischer** [comment]
Fixed this with https://github.com/robotology/wysiwyd/commit/399e81a61466a10198bb816f56bd06cf8842c08f
