### ISSUE TITLE
Tagging: the demo should use the bodypart name

### ISSUE THREAD

**Issue by maxime-petit** [robotology/wysiwyd#100]
Hi,

We can show without triggering any specific behavior that the bodypart name is learnt, by moving the corresponding joint when the robot ask the bodypart to be touched by the agent

./Max

**Comment by Tobias-Fischer** [comment]
Solved by https://github.com/robotology/wysiwyd/pull/103

Closing as soon as https://github.com/robotology/wysiwyd/pull/103 is merged
