### ISSUE TITLE
Agent Pointing: right hand should be seen in the GUI to help pointing

### ISSUE THREAD

**Issue by maxime-petit** [robotology/wysiwyd#101]
We already have the agent head in the GUI. Having the right hand might help to "properly" point (i.e. closest object to the hand location) and reduce wrong pointing detection

./Max

**Comment by Tobias-Fischer** [comment]
Hi @maxime-petit,
You can run `guiUpdater --displaySkeletons` to show all parts of the skeleton.

Guess this solves this issue.

Best, Tobi
