### ISSUE TITLE
narrativeHandler: look for the last X instances to extract stories

### ISSUE THREAD

**Issue by maxime-petit** [robotology/wysiwyd#105]
Instead of using the instantStart which depend on the ABM used, the range of ABM to be checked should use relative boundaries (e.g. [max-X:max]), and loaded from conf file.

This is to be able to manage how much time the ABM is querried at startup by narrative: it can be quite some time if you go through a large portion of ABM, and other modules might want to acces ABM in the meantime

./Max

**Comment by gregoire-pointeau** [comment]
A first update has been made to reduce considerably the number of request and the display.
@maxime-petit can you try it and tell me if the time is still to long.
I'll continue on the max*min later.

**Comment by gregoire-pointeau** [comment]
commit: https://github.com/robotology/wysiwyd/commit/f924a4f6345761759947184faaaead299fea7b7a
have added a min max (`instanceStart`, `instanceStop`) in the conf file.
However previous commit should have increase speed.
Please try on all your DB just to check if there is a significant improvement.

**Comment by Tobias-Fischer** [comment]
Hi @gregoire-pointeau,
Rather than defining absolute values, is it possible to define relative ones? We have dozens of new instances every day, which means that every day you would need to change the absolute value. What @maxime-petit wants is a relative value, i.e. take the last X instances instead of take instances Y to Z which was now implemented.

**Comment by gregoire-pointeau** [comment]
Ok,.
In the mean time, can you confirm that there is however an improvement in term of speed for starting?

**Comment by gregoire-pointeau** [comment]
There are now two more parameters:
`researchWindows`   default:   `1`      1 is window (min to max) while 0 is n-back
`nBackSize`   default `200`     size of the n-last instance to check.

**Comment by Tobias-Fischer** [comment]
Did you forget to commit?

**Comment by gregoire-pointeau** [comment]
...
maybe ...
