### ISSUE TITLE
SAM action recognition should be single module running

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#119]
Hi @dcam0050,

Please change SAM such that it does not spawn new windows. If you need to have separate processes, please launch them as threads rather than launching new processes in `xterm` windows.
For the visualization, you could have a separate window purely for this task retrieving the data from the main process. Or even better, use `yarpview` to do the job (it is very easy to stream an image through yarp).

I am strongly against the hack we used in Lyon for the Year 2 demo, this was only good for a very temporary solution.

Best,
Tobi
/cc @pattacini for software engineering questions

**Comment by Tobias-Fischer** [comment]
Furthermore, a pre-trained model should be provided. Training locally is not an option, the module should run out of the box. You should use `RFModule` to locate the model file (as well as any other configuration file). Hard coded paths are evil ..

**Comment by Tobias-Fischer** [comment]
Any news on this @dcam0050?

**Comment by dcam0050** [comment]
Working on it should release something in the next 2 weeks.

**Comment by dcam0050** [comment]
This is fixed with commit #147

**Comment by Tobias-Fischer** [comment]
Will close after merging https://github.com/robotology/wysiwyd/pull/147

**Comment by Tobias-Fischer** [comment]
Fixed in #147
