### ISSUE TITLE
SAM with dictionary of force results verb in the ABM

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/wysiwyd#120]
`SAM` action recognizer should be able to save recognized action into the ABM automatically.
Each action can have a distinction `force/result` (ie: `drop/fall` `push/moved`) that can be associated in an `.ini` file.

I can supervised the part about the recording in the `ABM`.

**Comment by Tobias-Fischer** [comment]
Hi @dcam0050, is this addressed in your PR? Is this still needed @gregoire-pointeau?

**Comment by gregoire-pointeau** [comment]
"Needed" I don't know.
It's just for SAM to be able to imagine different point of view.

**Comment by Tobias-Fischer** [comment]
@gregoire-pointeau @dcam0050 did you ever talk about this again? Do you think this will happen before the end of the year? Otherwise will close as `wontfix`.

**Comment by gregoire-pointeau** [comment]
We talked about sending all open class word from `LRH` to `SAM` but I guess the dictionary won't be set before the end of the year, we can close it I guess.
