### ISSUE TITLE
Cleaning the reactive layer modules

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#124]
That is:

- cleaning the `allostaticManager` code
- not using name-specific port names (for the time being the name of the ports depends on the name of the drives and behaviors)
- Creating the connections only in the XML.

**Comment by Tobias-Fischer** [comment]
@clement-moulin-frier Will this happen? Otherwise we might consider closing this.

**Comment by clement-moulin-frier** [comment]
Let's close it for the time being then, we'll reopen it if needed
