### ISSUE TITLE
iol2opc: Stream object names along with positions to port

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#132]
Hi,
@maxime-petit just had the idea that it would be nice to have the object names with positions provided by `iol2opc` streamed to a port. This would allow the `ABM` to have this information stored.

It should not take very long to do this.

Best,
Tobi

**Comment by pattacini** [comment]
No doubt it's doable without any particular pain. I guess this modification aims to alleviate `ABM` in its duty of retrieving those information easier than relying on requests to `OPC`, right?

**Comment by Tobias-Fischer** [comment]
Yes exactly :)

**Comment by Tobias-Fischer** [comment]
Done in https://github.com/robotology/wysiwyd/pull/142
