### ISSUE TITLE
Integrating the full language production/perception model from inserm to deal with complex sentences

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#137]
I.e. being able to deal with human request like "before grasping the banana, push the croco", both in language production and perception.

**Comment by Tobias-Fischer** [comment]
Hi @gregoire-pointeau,
was this included in your pull request? If not, will you be working on it, or shall we close this issue?

**Comment by gregoire-pointeau** [comment]
The comprehension/producation system now handle this kind of sentences (as you could see in the videos).
However for now it just segment the sentences, we don't forward meanings for example.
But technically speaking, `lrh` understand and produce these sentences.

**Comment by Tobias-Fischer** [comment]
Hi @gregoire-pointeau, can we close this issue?

**Comment by gregoire-pointeau** [comment]
Yes
