### ISSUE TITLE
Add parameters in conf file of `subSystem_KARMA` to modify the position of the `prepare` action

### ISSUE THREAD

**Issue by towardthesea** [robotology/wysiwyd#167]
Current `prepare` method in `subSystem_KARMA` brings both robot's arms to `hand-up` pose. The purpose of this issue is to solve the problem by providing the ability to tune this pose through config files. This issue will:
- Modify the `prepare` action to cope with parameters in config files
- Change `related` config files.

**Comment by Tobias-Fischer** [comment]
Is that addressed in #174 @towardthesea?

**Comment by towardthesea** [comment]
It is solved indeed!
