### ISSUE TITLE
Fix AppVeyor CI

### ISSUE THREAD

**Issue by pattacini** [robotology/wysiwyd#178]
Reminder to fix `AppVeyor` CI.

**Comment by Tobias-Fischer** [comment]
Seems like this is fixed (either @pattacini did some magic, or it decided to work by itself randomly). Shall we close @pattacini?

**Comment by pattacini** [comment]
Actually, I didn't do any magic 😮 
Perhaps AppVeyor was lazy ans stuck on its own...

Closing.
