### ISSUE TITLE
Pulling an object too close, preventing correct detection

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#213]
Hi,

When executing the plan `take`, often the robot pulls the object too close to itself, preventing it to be correctly detected when the post-condition is checked. In consequence the plan fails.

Is it possible to modify the `pull` behavior  so that the object remains in the visible area?

cc @towardthesea @pattacini @jypuigbo @sockchinglow

**Comment by Tobias-Fischer** [comment]
You can change the `backPos` of the `default.ini` of the `BM`. Just set it to a more negative value and give it a try. Best, Tobi

**Comment by towardthesea** [comment]
Thanks @Tobias-Fischer :smile:

**Comment by clement-moulin-frier** [comment]
Thanks guys (I remember one already told me this but I forgot ...)
It works much better with `backPos` to `-0.40`.
Should I push the change in `default.ini` or do we consider it as specific to the UPF setup?

**Comment by Tobias-Fischer** [comment]
You can push the change to the repo :). Closing as the issue seems resolved.
