### ISSUE TITLE
Narrative replies "Yes" to the question "What have you done the other day?"

### ISSUE THREAD

**Issue by jypuigbo** [robotology/wysiwyd#216]
And this sounds weird. Would be better if it replies something like "What do you want to know?", then the human says as usual "What happened first".

Where can we change this?

Thx

**Comment by Tobias-Fischer** [comment]
Hi,
you can change this here:
https://github.com/robotology/wysiwyd/blob/devel/main/src/modules/narrativeRelated/narrativeGraph/src/hri.cpp#L70-L74
It's randomly picking one of the values in `vBegin`. Let me know if this works.

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Fixed in https://github.com/robotology/wysiwyd/commit/ce09dff480228bfed97d10fb544ab58963d0fd72
