### ISSUE TITLE
Extend sensationManager to deal with both hands

### ISSUE THREAD

**Issue by towardthesea** [robotology/wysiwyd#218]
Current, the `sensationManger` only takes into account only the `right hand` of partner. It should be better and more natural if it can work with both hands.

@jypuigbo should be the best person to solve this one.

**Comment by Tobias-Fischer** [comment]
Fixed in https://github.com/robotology/wysiwyd/commit/7067e8242c9f7207e154c120184aea085b3a20f2 let's test and then close.

**Comment by jypuigbo** [comment]
Tested. Both hands are available now in `sensationManager` and both elicit activations of the `PPS`
