### ISSUE TITLE
Kinematc correspondance behavior doesn't stop

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#221]
Hi,

When asking "Can you find similar parts of my body", the robot shows it on screen, then point at my left hand (more or less). However, the behavior never stops, therefore blocking the demo.
Le'ts check this tomorrow when @Tobias-Fischer will be here.

Cheers,
Clément

**Comment by Tobias-Fischer** [comment]
Please update your system, see https://github.com/robotology/icub-main/commit/0b49fc997d4b8df05bddd0265f97977f204ce913
