### ISSUE TITLE
Rename iros2015 branch

### ISSUE THREAD

**Issue by pattacini** [robotology/wysiwyd#32]
@jypuigbo @clement-moulin-frier

**Comment by clement-moulin-frier** [comment]
Hi @pattacini 

We have to remove it from the remote repo indeed, we'll take care of this on Monday.

**Comment by pattacini** [comment]
:+1:

**Comment by clement-moulin-frier** [comment]
Hi @pattacini ,

Actually we need a remote repo to synchronize the version we are working on between ourselves. We generally use a branch on robotology/wysiwyd to do so, before merging to master when the code is stable. Is it problematic?

Another solution is to fork the repo on one of our github account. Why not but branching is normally the way to work on development versions.

Thanks to let us know

**Comment by pattacini** [comment]
No problem @clement-moulin-frier, keep using [**`iros2015`**](https://github.com/robotology/wysiwyd/tree/iros2015) for your convenience.

**Comment by Tobias-Fischer** [comment]
Can I suggest renaming `iros2015` to something more expressive, like `reactiveLayer` or `upf-devel` or something like that? ;)

**Comment by pattacini** [comment]
Good suggestion.

**Comment by clement-moulin-frier** [comment]
Ok excellent idea, I've just done it. 
Side question before closing the issue: do we still have to be careful that the compilation works on other branches than `master`? (i.e will travis try to compile the non-master branches?)
Thx

**Comment by clement-moulin-frier** [comment]
OK perfect
