### ISSUE TITLE
Change pasar to be able to deal with names different than "partner"

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#48]
Right now, pasar is relying on an agent called `partner` for the pointing detection etc. - this needs to be extended.

Anyone from UPF willing to take care of this? @jypuigbo @clement-moulin-frier @sockchinglow

**Comment by Tobias-Fischer** [comment]
This can be easily done using the commit for agentDetector (see https://github.com/robotology/wysiwyd/issues/51 and https://github.com/robotology/wysiwyd/commit/fb464122a4bfff79f04c96910136bb6615032916) as template. Someone please assign this issue to him/herself; let me know if you have questions.
@sockchinglow: This might be a good opportunity to get familiar with some of the core systems of WYSIWYD.

Best, Tobi

**Comment by gregoire-pointeau** [comment]
The kinect cannot detect more than one agent.
I would suggest to replace: `name = "partner"` by `isAgent()` and `name != "iCub"`

**Comment by Tobias-Fischer** [comment]
Ahhh I didn't know that. Works for me then!

**Comment by Tobias-Fischer** [comment]
Maybe `name!=iCub && name.doesnotstartwith("unknown") && isAgent()`?!?

Thanks for pointing this out @maxime-petit

**Comment by gregoire-pointeau** [comment]
Well it depends if we can have several agents in the opc. Normally yes (iCub + partner).
But kinect is only able to detect once at the time.
So if there is an agent which is not the iCub, it should be the partner no ?

**Comment by Tobias-Fischer** [comment]
Ahh yeah, for the pointing context it does not matter what the name of the partner is. We should still check the `isPresent` flag though.

Best,
Tobi

**Comment by gregoire-pointeau** [comment]
Indeed. So for pasar, I don't need to check that the name is not `unknown`, because an unknown agent can move or point anyway right ?

**Comment by Tobias-Fischer** [comment]
Yes, correct.

**Comment by maxime-petit** [comment]
In order to cope with potential improvements (e.g. buying a Kinect2 that allow multi-users skeleton) if you can rise a warning if there are more than one agent (not iCub) present (even if in that case you take the first one by default or something else)

It can also be used in that way for catching potential error of updating the presence of agents

**Comment by gregoire-pointeau** [comment]
Done.

**Comment by Tobias-Fischer** [comment]
:+1:
