### ISSUE TITLE
touchDetector crashes just before touching

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#49]
During the London integration meeting, we had the issue that `touchDetector` is crashing right at the moment when we try to detect the touch in the `proactiveTagging` module. We need to debug why and fix the issue.

Any volunteers?

**Comment by maxime-petit** [comment]
Can/Should we also add Bertrand for this?

**Comment by Tobias-Fischer** [comment]
Nah, I think the module is running very nicely otherwise and it only ever crashes if we read the port in the `proactiveTagging` module.
I'll have a look.

**Comment by Tobias-Fischer** [comment]
We just tried again, and it seems to work fine (without any changes). Closing until we find out otherwise.
