### ISSUE TITLE
Extend agentDetector to deal with several agents

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#51]
We had the issue in the integration meeting that `agentDetector` always detected an agent called `unknown` which is present, although there is another agent called `partner` which is the agent we actually want to recognize.
Further, I suggest to rename `unknown` to `unknown_agent`.

**Comment by stephane-lallee** [comment]
In fact there was a piece of code commented out within agent detector that was proceeding to face identification if the correct module was present. Then the skeleton would be named a d tracked properly. We never really used it, but if you have time to spend it is a required step toward the "ultimate child robot" ;-)

-----Message d'origine-----
De : "Tobias Fischer" <notifications@github.com>
Envoyé : ‎07/‎12/‎2015 21:01
À : "robotology/wysiwyd" <wysiwyd@noreply.github.com>
Objet : [wysiwyd] agentDetector should not detect unknown partner (#51)

We had the issue in the integration meeting that agentDetector always detected an agent called unknown which is present, although there is another agent called partner which is the agent we actually want to recognize.
Further, I suggest to rename unknown to unknown_agent.

**Comment by Tobias-Fischer** [comment]
@maxime-petit and I tackled this today, and will commit the updated version after some more tests. However, the drawback is that only one partner is allowed, so multiple skeletons will not show up. I guess we need to find a way to handle multiple simultaneous partners.

**Comment by Tobias-Fischer** [comment]
This is now working nicely, however still under the assumption that only one partner is in the scene. Also, `agentDetector` can now handle a partner named differently than `partner`, and the `iCubClient` automatically informs `agentDetector` if the name of an agent was changed (`changeName` method). Obviously, this needs to be extended, but I guess it's a good start.

**Comment by Tobias-Fischer** [comment]
Hi @gregoire-pointeau @maxime-petit @pattacini @clement-moulin-frier,
Do you think we need this for the year 2 demo? I guess it's good enough if we fix this for the year 3 demo.

Best, Tobi

**Comment by gregoire-pointeau** [comment]
See issues #43 for my opinion on different agents.

**Comment by Tobias-Fischer** [comment]
@dcam0050 are you planning to get face recognition running on the iCub (within WYSIWYD)? This would fix this problem. Look at the boolean variable `useFaceRecognition` and where it is used. Also, check `handleMultiplePlayers`.

In general, I think this issue would be best tackled at an integration meeting. Before tackling it, we should be very sure though that we end up using it. I am guessing it will easily take a full day before it's working nicely.

**Comment by Tobias-Fischer** [comment]
Hi @dcam0050 and @gregoire-pointeau,
I don't see this happening in the next few months, should we close this as `wontfix`?

**Comment by Tobias-Fischer** [comment]
Closing as `wontfix`, let be know if there are any objections.
