### ISSUE TITLE
Comparison to CHRIS project

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#55]
Someone should find out how our demo advances the work done in the CHRIS project: http://www.chrisfp7.eu/

**Comment by Tobias-Fischer** [comment]
@pattacini checked the table in https://github.com/robotology/wysiwyd/issues/77 and provided some more comments, so we can close here. Thanks!

Best, Tobi

**Comment by sockchinglow** [comment]
@pattacini has filled it in, closing this,
