### ISSUE TITLE
Comparison to POETICON(++) projects

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#56]
Someone should find out how our demo advances the work done in the POETICON and POETICON++ projects: http://www.poeticon.eu/ and http://poeticon.csri.gr/

**Comment by maxime-petit** [comment]
I ll check Poeticon++

**Comment by maxime-petit** [comment]
Replied on slack, comparable-project channel.

**Comment by Tobias-Fischer** [comment]
Thanks @maxime-petit. Closing.
