### ISSUE TITLE
PASAR handle burst of appareance and disappearance

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/wysiwyd#61]
PASAR should be able to detect when an object appears or disappears (given a timing of confidence as parameters).
PASAR should also send the information in the ABM (such as: "agent enters" or box disappeared).

**Comment by Tobias-Fischer** [comment]
@pattacini might be interested regarding the object stuff

**Comment by gregoire-pointeau** [comment]
Easy peazzy lemon squizzy !
