### ISSUE TITLE
Ears segfaulting and SpeechRecognizer blocking

### ISSUE THREAD

**Issue by jypuigbo** [robotology/wysiwyd#72]
I've been tracking the issue of ```ears``` unstability and I have maybe one first insight. 

```ears``` is currently trying to recognize something and it doesn't stop until it recognizes something This makes it a blocking module (so also slowing the flow of the ```proactiveTagging``` module). I added a couple of fixes that make it segfault less often, although don't solve this specific issue. 

I wanted to know if anyone here has tried or knows how the asynchronous recognition from the ```speechRecopgnizer``` works and if you think it might be a good alternative to solve the issue. 

This is more to open the discussion of what's the best way to proceed.

**Comment by Tobias-Fischer** [comment]
See also https://github.com/robotology/wysiwyd/issues/50

**Comment by Tobias-Fischer** [comment]
Did you push the fixes for `ears`?

**Comment by jypuigbo** [comment]
I think I committed but not pushed. Anyway, before I do, yesterday a discussion begun with @clement-moulin-frier : are we sure that 
```
if (yarp::os::Network::connect('partNameA', portNameB')){ do_something();}
```
does the same as
```
if (yarp::os::Network::isConnected('PA','PB')
{
    do_something();
}else{
yarp::os::Network::connect('PA', PB');
do_something();
}
```
Because I was seeing ```subsystem_recog``` disconnecting and reconnecting to ```ears```, when ```proactiveTagging``` was loading a new grammar. 

When this is clear, I'll push or change the commit.

**Comment by jypuigbo** [comment]
About the asynchronous part, I'll try to see if I can get how it works, as there's an rpc command to load/clear grammars asynchronously in ```speechRecognizer```.

**Comment by Tobias-Fischer** [comment]
I am not sure how the yarp internals work in these regards. Do you know @pattacini? Can you give us some insight in what you are trying to achieve?

**Comment by pattacini** [comment]
I think that a call to `yarp::os::Network::connect()` will first disconnect (if already connected) and then connect (again), whereas `yarp::os::Network::isConnected()` just queries the current status of the connection.

**Comment by jypuigbo** [comment]
Cool. I made the changes to avoid this dis/re-connecting happen again. 

I leave the issue open to continue working on the asynchronous recognition part.

**Comment by Tobias-Fischer** [comment]
See https://github.com/robotology/wysiwyd/commit/bb849b72f5d7cf1ac35f3623e090176eecbd7cf6

**Comment by Tobias-Fischer** [comment]
Hi @jypuigbo,
Do you plan to continue working on the asynchronous recognition part? If not, can we close here?

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Closing. Feel free to reopen @jypuigbo

**Comment by jypuigbo** [comment]
The problem seems to be tracked down thanks to @maxime-petit . 
I'm writing and issue to speech. The problem seems to be that, having two external grammars loaded, it keeps both active and doesn't send the output to both but to the last port. 

As soon as I get the post done I edit this one with the link.

**Comment by jypuigbo** [comment]
After testing, seems that the issue is no longer there. Pull requested in [[SpeechRecognizer] Added option to interrup #6](https://github.com/robotology/speech/pull/6). Pending confirmation.
