### ISSUE TITLE
Handle more actions

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#81]
For the time being we just deal with `pointing`. Try to add a few other actions, e.g. `looking`, `pushing` or `grasping` depending on what ARE is able to execute safely.

See also #45

**Comment by sockchinglow** [comment]
Creating a behaviour called glance for looking at something/someone for ~0.5seconds.

**Comment by jypuigbo** [comment]
We are solving this issue temporarily, as we have already some code regarding this, that we had no time to properly debug before coming to the integration, which was adding extra functionality. 

Adding as features: looking at X and pushing X

**Comment by Tobias-Fischer** [comment]
@jypuigbo @sockchinglow:
Can you please open a pull request so we can check this on the robot?

Best,
Tobi

**Comment by sockchinglow** [comment]
Handled in #84

**Comment by Tobias-Fischer** [comment]
Let's test this tomorrow morning, so we can close the issue.

**Comment by jypuigbo** [comment]
Ears now can listen to point, push and look_at, triggering the corresponding actions. Tested and debugged at UPF. Let me know of any additional fix needed.

**Comment by Tobias-Fischer** [comment]
Looking good. Thanks :)
