### ISSUE TITLE
Using persistent connections or not

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/wysiwyd#85]
Hi,

@pattacini pointed me to the possibility of [using persistent connections in YARP](http://www.yarp.it/persistent_connections.html), that allows an automatic reconnection whenever one port or the other is closed then reopened. It looks like an easy solution to avoid some issues we have about module dependencies.

However this solution could have side effects so we should think about where those connections can help us and where they should be avoided.

As an example, I tried to change all the connections made by `allostaticController` to `persistent` and some of them were not working correctly anymore (no idea about the reason). I then did it in only one of them and I obtained the expected behavior.

**Comment by Tobias-Fischer** [comment]
Hi @clement-moulin-frier,
As @pattacini said these connections might cause troubles. And you already found that `allostaticController` does not work properly with them, let alone all the other modules which run in our demo.
Thus, I think we should not make any use of them.

Best, Tobi

**Comment by clement-moulin-frier** [comment]
Not sure he said they can cause trouble, rather that we are loosing control by using them.

**Comment by pattacini** [comment]
I also feel to discourage the use of persistent connections for the time being. As we discussed, there is a specific procedure to disconnect a persistent connection and if we do not take it into account there's the serious risk of loosing control of the architecture.

**Comment by Tobias-Fischer** [comment]
I agree with @pattacini. Let's not use these connections, and rely on the connection list in `yarpmanager` instead. In the long term, we should change our modules to not automatically connect to others, and instead wait for the connection to be made outside.
Unfortunately, I don't see this happening anytime soon :(.

Closing here.
