### ISSUE TITLE
Tagging: priority should be to ask the agent's name

### ISSUE THREAD

**Issue by maxime-petit** [robotology/wysiwyd#98]
Hi,

Randomly picking object and bodypart is fine, but actually it makes more sense if the agent tagging a a higher priority over theses others two. Can we change the selection to automatically trigger partner tagging first as soon as name == partner?

@clement-moulin-frier @jypuigbo @sockchinglow 

./Max

**Comment by clement-moulin-frier** [comment]
OK @sockchinglow is on it.

**Comment by Tobias-Fischer** [comment]
Any news @sockchinglow?

**Comment by Tobias-Fischer** [comment]
Fixed in https://github.com/robotology/wysiwyd/pull/112
